apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ku6h4z5qt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/ku6h4z5qt-java-quarkus-gitops