apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ku6h4z5qt-java-quarkus
  janus-idp.io/tekton: ku6h4z5qt-java-quarkus
  backstage.io/kubernetes-id: ku6h4z5qt-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ku6h4z5qt-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
